# Generated by Django 3.2.7 on 2021-09-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userss',
        ),
    ]
